//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrdersEDITranslator
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserOptions
    {
        public int IdBtn { get; set; }
        public string Texto { get; set; }
        public Nullable<int> AccessLevel { get; set; }
        public string Clase { get; set; }
        public string Form { get; set; }
        public string Icono { get; set; }
        public string Taula { get; set; }
        public string Color { get; set; }
    }
}
